workflows:
  ios-release-workflow:
    name: iOS IPA Build (No Codesign)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        # 你可以在此处添加 SHOREBIRD_TOKEN，或者保持在 Codemagic UI 中设置
        SHOREBIRD_TOKEN: eyJyZWZyZXNoX3Rva2VuIjoiMS8vMDY1SEZ2XzBTa3h6T0NnWUlBUkFBR0FZU053Ri1MOUlyVmM2aXF2TjFNTmhyVHhTRi1LVlByZkhnTzR6TFVfblVqQlFpaVpTNkdRU2VYcEpxbC1nZDdsTVpWTGk3S19qb3pMZyIsImF1dGhfcHJvdmlkZXIiOiJnb29nbGUifQ==
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build and Package IPA
        script: |
          # 1. 运行构建命令（它会生成 .xcarchive，但跳过 ipa 导出）
          flutter build ipa --release --no-codesign
          
          # 2. 手动创建 Payload 结构（在 Mac 环境下操作，保留符号链接）
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/archive/Runner.xcarchive/Products/Applications/Runner.app build/ios/ipa/Payload/
          
          # 3. 压缩成标准的 .ipa 文件
          cd build/ios/ipa
          zip -r juhemusic.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - zhaozheng982@gmail.com
